### ISSUE TITLE
Project Link is Broken

### ISSUE THREAD

**Issue by jaredpetersen** [ShadowKyogre/mikidown#45]
The link at the top of the repository leads to a 404 page.

![screen shot 2015-05-24 at 4 11 26 pm](https://cloud.githubusercontent.com/assets/8802128/7790115/97f9533a-022f-11e5-955e-2900251fcdee.png)

**Comment by ShadowKyogre** [comment]
Fixed! Seems the redirect has expired now, so I fixed it to point to the unredirected version.

I'll definitely have more time to attend to this now that summer's here.
