### ISSUE TITLE
Support for RTL text

### ISSUE THREAD

**Issue by mjnaderi** [ShadowKyogre/mikidown#46]
Hello,

Is it possible to add a `dir="auto"` attribute to html elements like `p`, `h1`, `h2`, ..., `ul`, `ol`, to add support for right-to-left languages?

Thanks

**Comment by ShadowKyogre** [comment]
@mjnaderi: It's definitely possible, it's just a matter of how to approach it. I could code up something like the already existing Attribute List extension that takes a list of default attributes to put on every block level element (see https://pythonhosted.org/Markdown/extensions/attr_list.html).

There's also just going through the converted html and putting the dir="auto" manually, though that is more unsafe.

Before I proceed, can you show me how mikidown's rendering the text for you and how you expect it to be rendered (I've only got English on my dev computer)? Screenshots and markups would definitely be nice.

**Comment by mjnaderi** [comment]
Using this markup:
```
# Example

This is a LTR text. Next paragraph contains RTL text.

سلام. این یک متن فارسی است. و برای تست برنامه mikidown نوشته شده است.

This should be LTR:

* a
* b
* c

And this should be RTL:

* اول
* دوم
* سوم


Next heading should be RTL:

## مثال

```

I am getting this output:

![screenshot from 2015-07-02 01-27-28](https://cloud.githubusercontent.com/assets/2115303/8464738/bbe5b796-2059-11e5-84a0-56a7f477e7b8.png)

But I expect this:

![screenshot from 2015-07-02 01-30-41](https://cloud.githubusercontent.com/assets/2115303/8464781/0de922bc-205a-11e5-9da1-fd0607476ad4.png)

**Comment by ShadowKyogre** [comment]
@mjnaderi: Gotcha! I'll get to work on it straight away.

**Comment by ShadowKyogre** [comment]
Also, while I'm working on it, there's another case that I found that might be a problem if dir="auto" is put everywhere blindly (see the classroom convo):

http://dev.w3.org/html5/spec-preview/global-attributes.html#the-dir-attribute

The best work around I can think of is forcing the correct direction in certain cases while applying the dir attributes.

**Comment by mjnaderi** [comment]
@ShadowKyogre That's a good solution. I think detecting the true direction of paragraphs is not easy.

We can guess text direction in a better way by defining a `rtl_threshold`, and comparing `rtl_chars_count/all_chars_count` with `rtl_threshold`.

Twitter uses this method, and sets `rtl_threshold` to `0.3`.
https://github.com/twitter/RTLtextarea/blob/master/src/RTLText.module.js#L249

**Comment by ShadowKyogre** [comment]
@mjnaderi: Almost there with the extension to fix this, just gotta figure out how to deal with the bidi placeholders in markdown that're preventing fixes like the one you suggested.

Relevant lines of code I'm reading while figuring out a workaround: https://github.com/waylan/Python-Markdown/blob/e594213ab689847ee7d9654817b8fa80fafb0fb7/markdown/util.py#L38-L47

**Comment by ShadowKyogre** [comment]
@mjnaderi: Got a rough implementation of it so far, will polish it tomorrow with how Twitter does things.

Here's the test text I used that has both the classroom convo and your text:
~~~
# Example
    
This is a LTR text. Next paragraph contains RTL text.
    
سلام. این یک متن فارسی است. و برای تست برنامه mikidown نوشته شده است.
    
This should be LTR:
  
* a
* b
* c
    
And this should be RTL:
    
* اول
* دوم
* سوم
    
    
Next heading should be RTL:
    
## مثال


<b><bdi>Student</bdi>:</b> How do you write "What's your name?" in Arabic?

<b><bdi>Teacher</bdi>:</b> ما اسمك؟

<b><bdi>Student</bdi>:</b> Thanks.

<b><bdi>Teacher</bdi>:</b> That's written "شكرًا".

<b><bdi>Teacher</bdi>:</b> Do you know how to write "Please"?

<b><bdi>Student</bdi>:</b> "من فضلك", right?
~~~

**Comment by mjnaderi** [comment]
@ShadowKyogre Thanks for your attempt.
I tested it, and it didn't work correctly for these parts:
```
سلام. این یک متن فارسی است. و برای تست برنامه mikidown نوشته شده است.
```
This contains both rtl and ltr text, and is expected to be rtl, but becomes ltr.
```
* اول
* دوم
* سوم
```
This list contains only rtl text, but becomes ltr.

**Comment by ShadowKyogre** [comment]
https://github.com/ShadowKyogre/mikidown/commit/70ee73f392d76578e7be448e91e694987dab2977

Did a few more tweaks to address the UL and the orig Arabic+english txt. Tell me if there's any more examples where the text direction breaks!

**Comment by mjnaderi** [comment]
It is working find now. Thanks.

**Comment by ShadowKyogre** [comment]
Closing this, if there's any other texts this produces errors for, let me know.
