### ISSUE TITLE
Select editor font

### ISSUE THREAD

**Issue by mjnaderi** [ShadowKyogre/mikidown#48]
It would be great if there was an option to select the font and base font size of editor.

**Comment by mjnaderi** [comment]
Thanks for you fast implementation of this feature!

I tested it, and it's great. But I noticed that the font of `h1` and `h2` elements are different. And when I put a link, the font and font size of link look different from regular text.

![screenshot from 2015-07-04 01-12-27](https://cloud.githubusercontent.com/assets/2115303/8504624/f09de094-21e9-11e5-9598-a6e73752f9d1.png)

I mean there are some inconsistencies in text editor. It would be great if font and font size of different parts in editor were more consistent.

Adding an option for selecting monospace font is great too.

Thanks for your great effort

**Comment by ShadowKyogre** [comment]
@mjnaderi: That's partly due to how the original implementation of the highlighter highlights things. I'm planning to force those to not change their font size and family to ensure that it's consistent. 

It should be done around today to Sunday, because 4th of July weekend.

**Comment by ShadowKyogre** [comment]
@mjnaderi: Also, the screenshot you're showing for the link shows the link part as italicized. I don't think that's what you meant by it changes size, but, the h# ones are the ones that don't have sizes consistent with the rest of the highlighted text. I got the not forcing font size and family in highlighter done, just need to push it.

**Comment by ShadowKyogre** [comment]
Closing since it's implemented in commit (unless further feedback is given).
