### ISSUE TITLE
Copy/Paste plain text

### ISSUE THREAD

**Issue by mjnaderi** [ShadowKyogre/mikidown#49]
Sometimes user wants to copy pieces of text from websites to Mikidown. When I do this, html elements and styles are copied too. 

![screenshot from 2015-07-02 02-33-42](https://cloud.githubusercontent.com/assets/2115303/8465914/d7a17660-2062-11e5-98c3-98822471aef2.png)

I think, in most cases, user just wants plain text.

Maybe adding `paste rich text` to `Edit` menu, and setting the default action of `Ctrl+V` to `paste plain text` is a good solution.

**Comment by ShadowKyogre** [comment]
Note to self: This behavior is only present when html2text isn't present to markdownify a piece of text. See https://github.com/ShadowKyogre/mikidown/blob/develop/mikidown/mikiedit.py#L165-L172 for more information.

That being said, I'll probably also need to fiddle with the context menu to properly expose this to the user.

**Comment by ShadowKyogre** [comment]
Closing since it's implemented in commit (unless further feedback is given).
