### ISSUE TITLE
TeamWork

### ISSUE THREAD

**Issue by pedromorgan** [ShadowKyogre/mikidown#59]
Maybe we try
https://gitter.im

**Comment by pedromorgan** [comment]
@pedromorgan is in South Wales, Uk and GMT..

**Comment by ShadowKyogre** [comment]
We could do that and/or set up a channel on Freenode and/or contact each other over a protocol that'll allow leaving messages when either of us are offline (other than email, when all else fails). gitter.im has the overhead from browser usage (though there IS an IRC bridge I spotted for it. IDK how well the bridge works though).

**Comment by pedromorgan** [comment]
On gitter we can chat now.. ish no setup et all..

BTW same as all hackers, got a day job.. and a nite job. ;-))
