### ISSUE TITLE
Doesn't retain:

### ISSUE THREAD

**Issue by ghost** [ShadowKyogre/mikidown#6]
1. the window size and position (though I can work this out in KDE or Fluxbox),
2. the view mode (always launches in live mode) and so the cursor position. Retaining the cursor position (if possible) would be a convenience especially in longer documents.

**Comment by mjnaderi** [comment]
It would be nice if there was a field in notebook.conf for storing last view mode of the notebook. Then, for example, user gets the last view mode after turning off PC and coming back to it a few days later.
