### ISSUE TITLE
[Anaconda] Mikidown crash after create a new notebook

### ISSUE THREAD

**Issue by F-A** [ShadowKyogre/mikidown#70]
I just wanted to try out mikidown, but it crashes (Segmentation fault) everytime I try to create a new notebook.
Here are the message I see in the command line:

> locale/mikidown_fr_FR.qm
> ['./mikidown.py']
> Applying single instance per user lock.
> ['nl2br', 'strkundr', 'codehilite', 'fenced_code', 'headerid', 'headerlink', 'footnotes']
> PyQt4.QtCore.QUrl('file:///home/florian/mikinotes/css/search-window.css')
> PyQt4.QtCore.QUrl('file:///home/florian/mikinotes/css/notebook.css')
> Erreur de segmentation (core dumped)

"Erreur de segmentation" = "Segmentation fault"

I am using anacona for the python environment. Attached is the results of "conda list"
[packages_mikidown.txt](https://github.com/ShadowKyogre/mikidown/files/251839/packages_mikidown.txt)

Let me know if you need further information from the debug.

**Comment by ShadowKyogre** [comment]
For comparison, does the development branch segfault?

Also, have you tried running it without anaconda, just using plain python with the noted dependencies for the normal master branch?

I want to make sure this isn't an issue strictly related to running mikidown with anaconda (so I know where I can start with fixing this).

**Comment by F-A** [comment]
I'm sorry haven't tried to run it without anaconda but I would like to avoid installing all the packages in my Linux distribution directly... Sorry.

I'll give a try with the development branch but I need to install PyQ5 first. I'll come back to you when I have found time to test it.

**Comment by F-A** [comment]
I tried the master branch using the ubuntu packages instead of the anaconda ones and it work correctly.
Same for the develop branch using ubuntu packages. 

Also the problem could come from using mikidown with the anaconda packages.

**Comment by ShadowKyogre** [comment]
Huh, interesting. I'll try to reproduce it with anaconda on my end then. Sounds like there might be something in the anaconda bundled PyQt that I'm not accounting for then.

**Comment by ShadowKyogre** [comment]
Hrm, can't exactly get it to run with conda.
~~~~
╰[shadowkyogre@AlpheTerra]──────────────────────────[2016-05-11 (Wed) 17:03:20]╮
╭─[~/c/f/mikidown]─────────────────────────────────────────────────────────────╯
| ?master
╰─{($))>-< python ./mikidown.py                                   
Can't find slickpicker, falling back to QLineEdit for editing mikidown colors
/home/shadowkyogre/.themes/SKPotSunsetTrueDark/gtk-2.0/widgets.rc:76: Murrine configuration option "gradients" is no longer supported and will be ignored.
/home/shadowkyogre/.themes/SKPotSunsetTrueDark/gtk-2.0/widgets.rc:176: Background image options specified without filename
/home/shadowkyogre/.themes/SKPotSunsetTrueDark/gtk-2.0/widgets.rc:236: Background image options specified without filename
python: symbol lookup error: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: FcWeightFromOpenType
~~~~

Try using this patch that I just did on the develop today (edited for master): https://ptpb.pw/6kvn

Then place the two lines, properly indented, just after a notebook is created:
~~~~
from .utils import debugTrace
debugTrace()
~~~~

You should be able to get the precise line number of the segfault after this. To start, place the following two lines somewhere in this line range on master:

https://github.com/ShadowKyogre/mikidown/blob/master/mikidown/mikibook.py#L632-L636

**Comment by ShadowKyogre** [comment]
Whoops, meant this: https://github.com/ShadowKyogre/mikidown/blob/bd33d8451de5cb553805b0a7090a0488caa1ef66/mikidown/mikisearch.py#L22-L27

Being sleepy does things to pasting correct line references.

**Comment by F-A** [comment]
Sorry for the late response. I had few time to test it.

Adding the debugTrace function in the mikisearch.py or mikiview.py file did not help me to find where the segfault occured: it still happened without entering the debugger.

Then I found out, that the segfault occurs also when saving an edited notebook (pressing Ctrl+S).
I added the debugTrace fuunction at the beginning of the save function in mikiedit and here are my try with the debugger:



> \<path_to_mikidown\>/mikidown/mikidown/mikiedit.py(260)save()
-> debugTrace()
(Pdb) l
255  	        print('closed idx')
256  	        event.accept()
257  	    '''
258  	    def save(self, item):
259  	        from .utils import debugTrace
260  ->	        debugTrace()
261  	        pageName = self.parent.notesTree.itemToPage(item)
262  	
263  	        filePath = self.parent.notesTree.itemToFile(item)
264  	        htmlFile = self.parent.notesTree.itemToHtmlFile(item)
265  	
(Pdb) where
  \<path_to_mikidown\>/mikidown/mikidown.py(18)<module>()
-> mikidown.main()
  \<path_to_mikidown\>/mikidown/mikidown/__init__.py(113)main()
-> exit_code = app.exec_()
  \<path_to_mikidown\>/mikidown/mikidown/mikiwindow.py(626)saveCurrentNote()
-> self.saveNote(item)
  \<path_to_mikidown\>/mikidown/mikidown/mikiwindow.py(635)saveNote()
-> self.notesEdit.save(item)
> \<path_to_mikidown\>/mikidown/mikidown/mikiedit.py(260)save()
-> debugTrace()
(Pdb) s
Exited save note
Erreur de segmentation (core dumped)
> 

The "Exited save note" correspond to a print statement I added as a debug at the end of the mikiwindow.saveCurrentNote() function.
Interestingly the debugger cannot go to the next step, but if I add the debugtrace one line further, the debug mode is still activated before the segfault. Which means that the statement 
> pageName = self.parent.notesTree.itemToPage(item)
> 

is not the problem.
Anyway, my print statement at the end of the saveCurrentNote function is executed, so the segfault appears afterwards.

I'm sorry I could find where the problem actually is...
I'll probably use mikidown with the ubuntu packages since it is working without problem with them.

**Comment by pedromorgan** [comment]
@F-A  is this still a "annoying bug" and abandoned or are u in develop land ?

**Comment by F-A** [comment]
I had the bug only with the Anaconda distribution.
I'm currently using the Ubuntu packages instead and the bug is not present. So in my case it's no long an annoying bug.

**Comment by pedromorgan** [comment]
Think we can close this for now.. Open it as a new issue if we find the little snake.. ;-)
