### ISSUE TITLE
Document required version of python-asciimathml  in README

### ISSUE THREAD

**Issue by F-A** [ShadowKyogre/mikidown#71]
The default version of python-asciimathml available in pip is not compatible with python 3. 
As you mentioned in the changelogs notebook within mikidown, users need to install the python 3 compatible version of asciimathml.

However, using the default version, mikidown will start but the notes will not be displayed ad users have no chances to find out which version to install to use it with mikidown.

I would suggest to add with information directly in the README.mkd field, preferable in the dependence section.

**Comment by ShadowKyogre** [comment]
Hey there. Does this note here make it clearer for future users? - https://github.com/ShadowKyogre/mikidown/tree/develop#dependencies

**Comment by F-A** [comment]
Yes, this is clearer!
