### ISSUE TITLE
chat: irc.freenode.net#mikidown

### ISSUE THREAD

**Issue by pedromorgan** [ShadowKyogre/mikidown#80]
Maybe we need to register for fun is thats ok @ShadowKyogre 

Mainly for support.. if we get to GLOB ;-)

**Comment by pedromorgan** [comment]
https://github.com/ShadowKyogre/mikidown/issues/59

**Comment by ShadowKyogre** [comment]
Registered on freenode as #mikidown . I'll need to update the README when I get home. Last several months have been busy due to new job.
