### ISSUE TITLE
Newbie TODO: Tasks - take your pick ;-)

### ISSUE THREAD

**Issue by pedromorgan** [ShadowKyogre/mikidown#82]
For benefit of newbies who want to hack..
## Boring Tasks
- Removing all python4 stuff from eg **future** develop branch...Please walks each file and PR per file
- Install fabric and shpinx docs, create api-docs see `fab -l` in `develop`
# Huge Tactical Tasks
# file paths x-platform
- make the whole mikidown file path system easy for everyone https://github.com/ShadowKyogre/mikidown/issues/78
# Sys tray

https://github.com/ShadowKyogre/mikidown/issues/75

**Comment by ShadowKyogre** [comment]
> Removing all python4 stuff from eg future develop branch...Please walks each file and PR per file

I'm not sure what you're trying to say here.

Otherwise, there shouldn't be a master task list for all of these. But there should be labels in terms of difficulty.
